config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  
  get 'wikis/wiki_form' => 'wikis#wiki_form'
  get 'wikis/re_display' => 'wikis#re_display'
  get 'wikis/test' => 'wikis#test'
  get 'wikis/wikilist' => 'wikis#wikilist'
  get 'wikis/search' => 'wikis#search'
  post 'wiki_tags/delete_wiki_tag' => 'wiki_tags#delete_wiki_tag'
  post 'wikis/wiki_disable' => 'wikis#wiki_disable'
  post 'wiki_tags/new_wiki_tag' => 'wiki_tags#new_wiki_tag'
  get 'wiki_tags/menu' => 'wiki_tags#menu'

  resources :wikis
  resources :wiki_tags
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

	get "home/home", to: "home#home", as: :home_home
  post "home/contact(.:format)", to: "home#contact", as: :contact  
end

app/models/wiki.rb
class Wiki < ApplicationRecord
	belongs_to :user
	
	# gnarly many to many self join
	has_many :wiki_tags
	has_many :tags, through: "wiki_tags", :foreign_key => "tag_id", :class_name => "Wiki"	
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: %i[ show edit update destroy ]

  # GET /wikis or /wikis.json
  # GET /wikis
  # GET /wikis.json
  def index
    @wikis = Wiki.where("default_sort < 0 and (deleted is null or deleted is false)").order(default_sort: :desc)

    #???? nested_set doesn't work with mysql
    @menu = view_context.nested_set(view_context.query_menu,'tree-menu', 0)
    
    #might change recents to where < one month?
    @recents = Wiki.all.order(updated_at: :desc).limit(100)
  end

  # GET /wikis/1
  # GET /wikis/1.json
  def show
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
  end

  # GET /wikis/1/edit
  def edit
  end

  def test
     @wikis = WikiTag.all
  end

  def search

    if params[:search_text].present?
      @keywords = params[:search_text]
      wiki_search_term = WikiSearchTerm.new(@keywords)
      @wikis = Wiki.where(
      wiki_search_term.where_clause,
      wiki_search_term.where_args).
      order(wiki_search_term.order)
    else
      @wikis = []
    end


    @menu = view_context.nested_set(view_context.query_menu,'tree-menu', 0)
    #might change recents to where < one month?
    @recents = Wiki.all.order(updated_at: :desc).limit(100)
    render template: "wikis/index"
  end  

  def wikilist
     @wikis = Wiki.all
  end

  # POST /wikis
  # POST /wikis.json
  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user_id = current_user.id
    @wiki_id = 0

    respond_to do |format|    
      if @wiki.save
        create_parent_tag(@wiki)
        if @wiki.default_sort == 0
          @wiki.update(:default_sort => @wiki.id)
        end
        format.html { redirect_to wikis_url, notice: 'Wiki was successfully created.' }
        format.js { render "wikis/display" }
      else
        format.html { render :new }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wikis/1
  # PATCH/PUT /wikis/1.json
  def update

    @wiki_id = @wiki.id
    respond_to do |format|
      if @wiki.update(wiki_params)
        format.html { redirect_to wikis_url, notice: 'Wiki was successfully updated.' }
        format.js { render "wikis/display" }
      else
        format.html { render :edit }
        format.json { render json: @wiki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wikis/1
  # DELETE /wikis/1.json
  def destroy
    @wiki.destroy
    respond_to do |format|
      format.html { redirect_to wikis_wikilist_url, notice: 'Wiki was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def wiki_form
    @wikis = Wiki.all.order(title: :asc)
    @new_journal = false

    if params[:wiki_id] != "0"
      @wiki = Wiki.find(params[:wiki_id])
    else
      @wiki = Wiki.new
    end

    if params[:wiki_type] == "j"
      @wiki.title = Time.now.to_formatted_s(:stardate)
      @new_journal = true
    end  

    respond_to do |format|
      format.html { render layout: false}
      format.json { render nothing: true }
    end 
  end  

  def re_display
    @wiki = Wiki.find(params[:wiki_id])

    respond_to do |format|
      format.html { render layout: false}
      format.json { render nothing: true }
    end 
  end 

  def wiki_disable
    
    wiki = Wiki.find(params[:wiki_id]);
    wiki.deleted = true;

    respond_to do |format|
      if wiki.save
        format.html { render nothing: true }
        format.js { render nothing: true }
      else
        format.html { render nothing: true }
        format.js { render nothing: true }
      end
    end

  end

  private

    def create_parent_tag(wiki)
      if !wiki.parent.nil?
        wiki_tag = WikiTag.new({:wiki_id => wiki.id, :tag_id => wiki.parent})
        wiki_tag.save
      elsif wiki.title.match('\d{4}\.')
        journal = Wiki.where("title = 'Journal'").first
        #raise journal.inspect
        if !journal.nil?
          wiki_tag = WikiTag.new({:wiki_id => wiki.id, :tag_id => journal.id})
          wiki_tag.save            
        end
      else
        #Rails.log.info("No tag for you!")  
        #Rails.log.info("~~~~~~~~~~~~~~~~~~~~~~~~~~~~")  
      end

    end  
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wiki_params
      params.require(:wiki).permit(:title, :user_id, :body, :parent, :version, :deleted, :default_sort, :last_revision)
    end
end

app/helpers/wikis_helper.rb
module WikisHelper

  def nested_set(nested_set_query,link_class, parent_id)

    current_level = 1
    first_item = true
      
    menu = "<ul class='nav nav-list'>"
    tree_toggler = "<i class='tree-toggler nav-header fa fa-chevron-right' aria-hidden='true'></i>"

    nested_set_query.each do |link|
      if !link.id.nil? and !link.path.nil?
      if current_level < link.path.length
        menu += " <ul class='nav nav-list tree'>"
      elsif current_level > link.path.length
        menu += "</li></ul>" * (current_level-link.path.length)
      elsif !first_item  
        menu += "</li>"
      else  
        first_item = false
      end
      menu += "<li>#{tree_toggler}<a href='javascript:void(0);' data-wiki-id='#{link.id}' data-parent-id='#{parent_id}' class='#{link_class}'>#{link.title}</a>"
      current_level = link.path.length
      end
    end  

    menu += "</li>"
    menu += ("</ul>" * current_level)

    return menu

  end

    def query_menu
      Wiki.find_by_sql("WITH RECURSIVE category_tree(id, path, my_sort) AS (

      select wikis.id, ARRAY[wikis.id], ARRAY[wikis.default_sort]
      from wikis left outer join wiki_tags on wikis.id = wiki_tags.wiki_id
      where wiki_tags.tag_id is null and (wikis.deleted is null or wikis.deleted is false)

      UNION ALL
      SELECT wiki_tags.wiki_id as id, path || wiki_tags.wiki_id, my_sort || wikis.default_sort
      FROM category_tree
      JOIN wiki_tags ON wiki_tags.tag_id=category_tree.id
      JOIN wikis ON wikis.id=wiki_tags.wiki_id
      WHERE NOT wiki_tags.wiki_id = ANY(path)
      )


      SELECT category_tree.*, wikis.title, wikis.default_sort 
      FROM category_tree 
            RIGHT OUTER JOIN wikis on category_tree.id = wikis.id
      ORDER BY my_sort")
    end  

    def query_toc(id)
      Wiki.find_by_sql("WITH RECURSIVE category_tree(id, path, my_sort) AS (

      select wikis.id, ARRAY[wikis.id], ARRAY[wikis.default_sort]
      from wikis left outer join wiki_tags on wikis.id = wiki_tags.wiki_id
      where wiki_tags.tag_id = #{id} and (wikis.deleted is null or wikis.deleted is false)

      UNION ALL
      SELECT wiki_tags.wiki_id as id, path || wiki_tags.wiki_id, my_sort || wikis.default_sort
      FROM category_tree
      JOIN wiki_tags ON wiki_tags.tag_id=category_tree.id
      JOIN wikis ON wikis.id=wiki_tags.wiki_id
      WHERE NOT wiki_tags.wiki_id = ANY(path)
      )


      SELECT category_tree.*, wikis.title, wikis.default_sort 
      FROM category_tree 
            RIGHT OUTER JOIN wikis on category_tree.id = wikis.id
      ORDER BY my_sort, wikis.created_at desc")
    end 


end

app/views/wikis/_display.html.haml
.panel-heading
  .row
    .col-md-9.wiki-tags
      %p.wiki-title= wiki.title
      %p.wiki-tags
        - wiki.wiki_tags.each do |wiki_tag|
          - if !wiki_tag.tag.nil?
            %a.btn.btn-tag{"data-tag-id" => "#{wiki_tag.tag_id}", "data-this-id" => "#{wiki.id}", href: "javascript:void(0)"}= wiki_tag.tag.title
    .col-md-3.wiki-actions.right
      %i.fas.fa-plus.action-icon.wiki-here{"aria-hidden" => "false", "data-id" => "#{wiki.id}", "data-parent" => "#{wiki.title}", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Create a child wiki2."}
      - if current_user.id == wiki.user.id or current_user.admin?
        %i.fas.fa-pencil-alt.action-icon.wiki-edit{"aria-hidden" => "false", "data-id" => "#{wiki.id}", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Edit this wiki."}
      %i.far.fa-times-circle.action-icon.wiki-remove{"aria-hidden" => "false", "data-id" => "#{wiki.id}", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Remove this wiki from the page."}
.panel-body
  .row
    .col-md-12.wiki-body
      - if wiki.body.include? "{{TOC}}"
        - wiki.body["{{TOC}}"] = nested_set(query_toc(wiki.id),'wiki-menu', wiki.id)
      = wiki.body.html_safe
.panel-footer
  .row
    .col-md-12.wiki-attributes
      Author: #{wiki.user.id if !wiki.user.nil?} (version: #{current_user.id} #{"deleted" if wiki.deleted?}) | ID: #{wiki.id} |
      Created:  #{wiki.created_at.in_time_zone('Indiana (East)').to_formatted_s(:stardatetime)} | Updated: #{wiki.updated_at.in_time_zone('Indiana (East)').to_formatted_s(:stardatetime)}
      %br/

app/views/wikis/_form.html.haml
= form_for(@wiki) do |f|
  - if @wiki.errors.any?
    #error_explanation
      %h2
        = pluralize(@wiki.errors.count, "error")
        prohibited this wiki from being saved:
      %ul
        - @wiki.errors.full_messages.each do |message|
          %li= message
  .panel-heading
    %h3.panel-title
      = f.label :title
      = f.text_field :title
  .panel-body
    .row.border-bottom
      .col-md-6.wiki-tags
        = f.label :parent
        = f.text_field :parent
      .col-md-6.wiki-tags
        = f.label :default_sort
        = f.text_field :default_sort
      .col-md-6.wiki-tags
        = f.label :deleted
        = f.check_box :deleted
      .col-md-6.wiki-actions.right
        %button.btn-transparent{name: "commit", type: "submit"}
          %i.fa.fa-check-square-o.action-icon{"aria-hidden" => "false"}
        = link_to @wiki, method: :delete, data: { confirm: 'Are you sure?' } do
          %i.fa.fa-trash{"aria-hidden" => "false", style: "font-size:2rem;color:red;"}
    .row.wiki-body
      = f.label :body
      = f.input :body, class: "wiki-body-body"
  .panel-footer
    .row.wiki-attributes
      Author: #{current_user.login}

:javascript
  $( document ).ready(function() {
    tinyMCE.init({
      selector: '#wiki-body-body',
      height: 500,
      menubar: "",
      plugins: "image link charmap advlist fullscreen code",
      toolbar: "fullscreen | undo redo | styleselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist outdent indent | removeformat | image | link | charmap | code | help",
      content_css: "#{ asset_path('application.css')}"
    });

  })      

app/views/wikis/_list.html.haml
- @wikis.each do |wiki|
  .panel.panel-default.wiki-panel{id: "#{wiki.id}"}
    = render "display", :wiki => wiki

app/views/wikis/_refresh_display.html.haml
.panel-heading
  .row
    .col-md-9.wiki-tags
      %p.wiki-title= @wiki.title
      %p.wiki-tags
        - @wiki.wiki_tags.each do |wiki_tag|
          - if !wiki_tag.tag.nil?
            %a.btn.btn-tag{"data-tag-id" => "#{wiki_tag.tag_id}", "data-this-id" => "#{@wiki.id}", href: "javascript:void(0)"}= wiki_tag.tag.title
    .col-md-3.wiki-actions.right
      %i.fas.fa-plus.action-icon.wiki-here{"aria-hidden" => "false", "data-id" => "#{@wiki.id}", "data-parent" => "#{@wiki.title}", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Create a child wiki."}
      %i.fas.fa-pencil-alt.action-icon.wiki-edit{"aria-hidden" => "false", "data-id" => "#{@wiki.id}", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Edit this wiki."}
      %i.far.fa-times-circle.action-icon.wiki-remove{"aria-hidden" => "false", "data-id" => "#{@wiki.id}", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Remove this wiki from the page."}
.panel-body
  .row
    .col-md-12.wiki-body
      - if @wiki.body.include? "{{TOC}}"
        - @wiki.body["{{TOC}}"] = nested_set(query_toc(@wiki.id),'wiki-menu', @wiki.id)
      = @wiki.body.html_safe
.panel-footer
  .row
    .col-md-12.wiki-attributes
      Author: #{@wiki.user.login if !@wiki.user.nil?} (version: #{@wiki.version} #{"deleted" if @wiki.deleted?}) | ID: #{@wiki.id} |
      Created:  #{@wiki.created_at.strftime("%Y-%m-%d %R")} | Updated: #{@wiki.updated_at.strftime("%Y-%m-%d %R")}
      %br/

app/views/wikis/_sidebar.html.haml
.white-scroller.sidebar-content
  %p{id: "sidebar-actions pull-right"}
    %i#wiki-new.fas.fa-plus.action-icon{"aria-hidden" => "false", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Add a new wiki."}
    %i#wiki-new-journal.fas.fa-file-alt.action-icon{"aria-hidden" => "false", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Add a new journal."}
    = link_to wikis_path do
      %i#wiki-home.fa.fa-home.action-icon{"aria-hidden" => "false", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Display home wikis."}
  = form_tag(wikis_search_path, id: "search-form", method: :get) do
    .input-group
      %input.form-control{"aria-describedby" => "wiki-search", "aria-label" => "Search", name: "search_text", placeholder: "search", type: "text"}/
      %span#wiki-search.input-group-addon
        %i.fa.fa-search.action-icon{"aria-hidden" => "false", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Search wiki contents."}
  %ul#sidebarTabs.nav.nav-tabs
    %li.active
      %a{"data-target" => "#menu", "data-toggle" => "tab"} Menu
    %li
      %a{"data-target" => "#open", "data-toggle" => "tab"} Open
    %li
      %a{"data-target" => "#recent", "data-toggle" => "tab"} Recent
  .tab-content
    #menu.tab-pane.active
      .well.nested-menu{style: "width:100%; padding: 8px 0;"}= @menu.html_safe
    #open.tab-pane
      %ul.nav.nav-list
        - @wikis.each do |wiki_link|
          %li
            %a.tree-menu{"data-wiki-id" => "#{wiki_link.id}", href: "javascript:void(0);"}= wiki_link.title
    #recent.tab-pane
      %ul.recent-list
        - group_date = ""
        - @recents.each do |recent_link|
          - if group_date != recent_link.updated_at.strftime('%F')
            - group_date = recent_link.updated_at.strftime('%F')
            %li.recent-group= group_date
          %li
            %a.tree-menu{"data-wiki-id" => "#{recent_link.id}", href: "javascript:void(0);"}= recent_link.title

app/views/wikis/display.js.erb
$("#<%=@wiki_id%>").html('<%= j render "wikis/refresh_display" %>');
$("#<%=@wiki_id%>").attr('id','<%= @wiki.id %>');
bindDisplayActionIcons();

app/views/wikis/edit.html.haml
.row{style: "margin-top:40px;"}
  .col-md-4.col-md-offset-4.col-xs-12.white-scroller
    %h1 Edit Wiki
    = render 'form'

app/views/wikis/index.html.haml
%nav.navbar.navbar-fixed-top{style: "top:52px;"}
  .sidebar-date.pull-right
    Today is #{DateTime.now.in_time_zone('Indiana (East)').to_formatted_s(:stardate)}   
    %i.fa.fa-chevron-right.sidebar-toggle{"aria-hidden" => "false", "data-placement" => "left", "data-toggle" => "tooltip", title: "Show/Hide Sidebar."}
#row-main.row
  #mySidenav.sidenav.sidenav-open
    = render "sidebar"
  #main.main-collapsed
    = render "list"

app/views/wikis/new.html.haml
.row{style: "margin-top:40px;"}
  .col-md-4.col-md-offset-4.col-xs-12.white-scroller
    %h1 New Wiki
    = render 'form'

app/views/wikis/re_display.html.haml
= render "refresh_display"

app/views/wikis/show.html.haml
%p
  %strong Title:
  = @wiki.title
%p
  %strong Author:
  = @wiki.user.inspect
%p
  %strong Body:
  = @wiki.body
%p
  %strong Parent:
  = @wiki.parent
%p
  %strong Revision:
  = @wiki.prev_revision
%p
  %strong Deleted:
  = @wiki.deleted
= link_to 'Edit', edit_wiki_path(@wiki)
|
= link_to 'Back', wikis_path
= @wiki.inspect

app/views/wikis/test.html.haml
.row
  .col-md-1
  .col-md-10.white-scroller
    %h1 Tags
    %table.responsive-table{style: "margin:auto;width:100%;"}
      %thead
        %tr
          %th Wiki ID
          %th Tag ID
          %th Tag Title
      %tbody
        - @wikis.each do |wiki_tag|
          %tr
            %td= wiki_tag.wiki_id
            %td= wiki_tag.tag_id
            %td= wiki_tag.tag.title if !wiki_tag.tag.nil?

app/views/wikis/wiki_form.html.haml
%datalist#tag_list
  - @wikis.each do |tag|
    %option{value: "#{tag.id}"}= tag.title
= simple_form_for(@wiki, :html => {:class => "wiki-form", :remote=>true}) do |f|
  - if @wiki.errors.any?
    #error_explanation
      %h2
        = pluralize(@wiki.errors.count, "error")
        prohibited this wiki from being saved:
      %ul
        - @wiki.errors.full_messages.each do |message|
          %li= message
  .panel-heading
    .row
      .col-md-10.wiki-tags
        %p.wiki-title{style: "max-width:100%;"}
          = f.label :title
          = f.text_field :title, class: "form-control"
      .col-md-2.wiki-actions.right
        %button.btn-transparent{"data-placement" => "bottom", "data-toggle" => "tooltip", name: "commit", title: "Save changes to this wiki.", type: "submit"}
          %i#wiki-save.far.fa-check-square.action-icon{"aria-hidden" => "false"}
        %i#wiki-cancel.far.fa-window-close.action-icon{"aria-hidden" => "false", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Close wiki without saving."}
        %i.fa.fa-trash.action-icon.wiki-delete{"aria-hidden" => "false", "data-id" => "#{@wiki.id}", "data-placement" => "bottom", "data-toggle" => "tooltip", title: "Inactivate this wiki."}
  .panel-body
    = f.label "Tags"
    .row
      .col-md-3
        .input-group{style: "max-width:300px;"}
          %input#input-tag.form-control{"aria-describedby" => "add-tag", "aria-label" => "Wiki tag", list: "tag_list", placeholder: "Type or Select Tag", type: "text"}/
          %span#add-tag.input-group-addon{"data-wiki-id" => "#{@wiki.id}"} Add
      #tag-tray.col-md-8
        - @wiki.wiki_tags.each do |wiki_tag|
          - if !wiki_tag.tag.nil?
            %a.btn.tag-delete{"data-placement" => "bottom", "data-tag" => "#{wiki_tag.id}", "data-toggle" => "tooltip", "data-wiki" => "#{@wiki.id}", href: "javascript:void(0)", title: "Remove this tag."}
              %i.fa.fa-trash{"aria-hidden" => "false"}
              = wiki_tag.tag.title
        - if @new_journal
          %span.btn.btn-tag Journal
    .row
      .col-md-4.col-sm-12
        .input-group{style: "max-width:300px;"}
          = f.label :"Show on Home Screen"
          = f.text_field :default_sort, class: "form-control"
    .row
      .col-md-12.wiki-body
        = f.input :body, class: "wiki-body-body"
        = f.hidden_field :authenticity_token, value: form_authenticity_token
        = f.hidden_field :parent
  .panel-footer
    .row
      .col-md-12.wiki-attributes
        Author: #{current_user.login} |
        Created:  #{Time.now.strftime("%Y-%m-%d %R")}

:javascript
  $( document ).ready(function() {
    tinyMCE.init({
      selector: '#wiki_body',
      height: 500,
      menubar: "",
      plugins: "image link charmap advlist fullscreen code",
      toolbar: "fullscreen | undo redo | styleselect | bold italic backcolor  | alignleft aligncenter alignright alignjustify | bullist outdent indent | removeformat | image | link | charmap | code | help",
      content_css: "#{ asset_path('application.css')}"
    });
    window._token = '#{form_authenticity_token}'
  })

app/views/wikis/wikilist.html.haml
.row{style: "margin-top:40px;"}
  .col-md-8.col-md-offset-2.col-xs-12.white-scroller
    %h1 Listing Wiki Tags
    %table.table
      %thead
        %tr
          %th ID
          %th Title
          %th User
          %th Parent
          %th Version
          %th Deleted
          %th Created
          %th Updated
          %th Last Revision
          %th Default Sort
          %th{colspan: "3"}
      %tbody
        - @wikis.each do |wiki|
          %tr
            %td= wiki.id
            %td= wiki.title
            %td= wiki.user_id
            %td= wiki.parent
            %td= wiki.version
            %td= wiki.deleted
            %td= wiki.created_at
            %td= wiki.updated_at
            %td= wiki.last_revision
            %td= wiki.default_sort
            %td= link_to 'Show', wiki
            %td= link_to 'Edit', edit_wiki_path(wiki)
            %td= link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' }
    %br/
    = link_to 'New Wiki tag', new_wiki_tag_path