config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  
  get 'wikis/wiki_form' => 'wikis#wiki_form'
  get 'wikis/re_display' => 'wikis#re_display'
  get 'wikis/test' => 'wikis#test'
  get 'wikis/wikilist' => 'wikis#wikilist'
  get 'wikis/search' => 'wikis#search'
  post 'wiki_tags/delete_wiki_tag' => 'wiki_tags#delete_wiki_tag'
  post 'wikis/wiki_disable' => 'wikis#wiki_disable'
  post 'wiki_tags/new_wiki_tag' => 'wiki_tags#new_wiki_tag'
  get 'wiki_tags/menu' => 'wiki_tags#menu'

  resources :wikis
  resources :wiki_tags
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

	get "home/home", to: "home#home", as: :home_home
  post "home/contact(.:format)", to: "home#contact", as: :contact  
end

app/models/wiki_tag.rb
class WikiTag < ApplicationRecord
	belongs_to :wiki
  belongs_to :tag, :foreign_key => "tag_id", :class_name => "Wiki"
end

app/controllers/wiki_tags_controller.rb
class WikiTagsController < ApplicationController
  before_action :set_wiki_tag, only: %i[ show edit update destroy ]

  # GET /wiki_tags or /wiki_tags.json
  def index
    @wiki_tags = WikiTag.all
  end

  # GET /wiki_tags/1 or /wiki_tags/1.json
  def show
  end

  # GET /wiki_tags/new
  def new
    @wiki_tag = WikiTag.new
  end

  # GET /wiki_tags/1/edit
  def edit
  end

  # POST /wiki_tags or /wiki_tags.json
  def create
    @wiki_tag = WikiTag.new(wiki_tag_params)

    respond_to do |format|
      if @wiki_tag.save
        format.html { redirect_to wiki_tag_url(@wiki_tag), notice: "Wiki tag was successfully created." }
        format.json { render :show, status: :created, location: @wiki_tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_tags/1 or /wiki_tags/1.json
  def update
    respond_to do |format|
      if @wiki_tag.update(wiki_tag_params)
        format.html { redirect_to wiki_tag_url(@wiki_tag), notice: "Wiki tag was successfully updated." }
        format.json { render :show, status: :ok, location: @wiki_tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_tags/1 or /wiki_tags/1.json
  def destroy
    @wiki_tag.destroy

    respond_to do |format|
      format.html { redirect_to wiki_tags_url, notice: "Wiki tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def delete_wiki_tag
 
    WikiTag.find(params[:id]).destroy
    
    respond_to do |format|
      format.html { render nothing: true }
      format.js { render nothing: true }
    end    
  end

  def new_wiki_tag
    
    @wiki_tag = WikiTag.new({:wiki_id => params[:wiki_id], :tag_id => params[:tag_id]})

    respond_to do |format|
      if @wiki_tag.save
        format.js { render :json => @wiki_tag.id }
      else
        format.html { render nothing: true }
        format.js { render nothing: true }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki_tag
      @wiki_tag = WikiTag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wiki_tag_params
      params.require(:wiki_tag).permit(:wiki_id, :tag_id)
    end
end

app/helpers/wiki_tags_helper.rb
module WikiTagsHelper
end

app/views/wiki_tags/_form.html.erb
<%= form_for(@wiki_tag) do |f| %>
  <% if @wiki_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki_tag.errors.count, "error") %> prohibited this wiki_tag from being saved:</h2>

      <ul>
      <% @wiki_tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :wiki_id %><br>
    <%= f.number_field :wiki_id %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.number_field :tag_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wiki_tags/_form.html.haml
= form_for @wiki_tag do |f|
  - if @wiki_tag.errors.any?
    #error_explanation
      %h2= "#{pluralize(@wiki_tag.errors.count, "error")} prohibited this wiki_tag from being saved:"
      %ul
        - @wiki_tag.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :wiki_id
    = f.number_field :wiki_id
  .field
    = f.label :tag_id
    = f.number_field :tag_id
  .actions
    = f.submit 'Save'

app/views/wiki_tags/edit.html.erb
<div class="row" style="margin-top:40px;">
<div class="col-md-4 col-md-offset-4 col-xs-12  white-scroller" >

<h1>Editing Wiki Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @wiki_tag %> |
<%= link_to 'Back', wiki_tags_path %>

</div>
</div>

app/views/wiki_tags/edit.html.haml
%h1 Editing wiki_tag

= render 'form'

= link_to 'Show', @wiki_tag
\|
= link_to 'Back', wiki_tags_path

app/views/wiki_tags/index.html.erb
<div class="row" style="margin-top:40px;">
<div class="col-md-4 col-md-offset-4 col-xs-12  white-scroller" >

<p id="notice"><%= notice %></p>

<h1>Listing Wiki Tags</h1>

<table class="table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Wiki</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wiki_tags.each do |wiki_tag| %>
      <tr>
        <td><%= wiki_tag.id %></td>
        <td><%= wiki_tag.wiki_id %></td>
        <td><%= wiki_tag.tag_id %></td>
        <td><%= link_to 'Show', wiki_tag %></td>
        <td><%= link_to 'Edit', edit_wiki_tag_path(wiki_tag) %></td>
        <td><%= link_to 'Destroy', wiki_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wiki tag', new_wiki_tag_path %>

</div>
</div>

app/views/wiki_tags/index.html.haml
%h1 Listing wiki_tags

%table
  %thead
    %tr
      %th Wiki
      %th Tag
      %th
      %th
      %th

  %tbody
    - @wiki_tags.each do |wiki_tag|
      %tr
        %td= wiki_tag.wiki_id
        %td= wiki_tag.tag_id
        %td= link_to 'Show', wiki_tag
        %td= link_to 'Edit', edit_wiki_tag_path(wiki_tag)
        %td= link_to 'Destroy', wiki_tag, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Wiki tag', new_wiki_tag_path

app/views/wiki_tags/menu.html.erb
<% @wiki_menu.each do |tag| %>
	ID: <%= tag.id %>  | Title: <%= tag.title %> | Path: <%= tag.path.inspect %> | Sort: <%= tag.my_sort.inspect %> | Default Sort: <%= tag.default_sort %><br/>
	<hr>
<% end %>

app/views/wiki_tags/new.html.erb
<h1>New Wiki Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', wiki_tags_path %>

app/views/wiki_tags/new.html.haml
%h1 New wiki_tag

= render 'form'

= link_to 'Back', wiki_tags_path

app/views/wiki_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @wiki_tag.id %>
</p>

<p>
  <strong>Wiki:</strong>
  <%= @wiki_tag.wiki_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @wiki_tag.tag_id %>
</p>

<%= link_to 'Edit', edit_wiki_tag_path(@wiki_tag) %> |
<%= link_to 'Back', wiki_tags_path %>

app/views/wiki_tags/show.html.haml
%p#notice= notice

%p
  %b Wiki:
  = @wiki_tag.wiki_id
%p
  %b Tag:
  = @wiki_tag.tag_id

= link_to 'Edit', edit_wiki_tag_path(@wiki_tag)
\|
= link_to 'Back', wiki_tags_path